### ISSUE TITLE
[ERROR] nil pointer dereference

### ISSUE THREAD

**Issue by shaorui0** [intel/kubernetes-power-manager#22]
Hi,
I followed the instruction to deploy the kubernetes-power-manager and then I applied an example-cstates.yaml. 
But there are some bugs that I can't pinpoint.

logs:
```
1.6660929253109546e+09  INFO    controllers.PowerProfile        Power Profile successfully created: Name - performance Max - 3500 Min - 3300 EPP - performance     {"powerprofile": "intel-power/performance"}
1.666092925412031e+09   INFO    controllers.CState      Successfully Applied new CStates config {"cStates": "default/master"}
1.666092930108173e+09   INFO    Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference        {"controller": "powernode", "controllerGroup": "power.intel.com", "controllerKind": "PowerNode", "powerNode": {"name":"master","namespace":"intel-power"}, "namespace": "intel-power", "name": "master", "reconcileID": "fb07ca1b-1ed9-40ec-b159-8e4b931a0fa2"}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1473e14]

goroutine 443 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:118 +0x1f4
panic({0x15d8300, 0x2545b70})
        /usr/local/go/src/runtime/panic.go:838 +0x207
github.com/intel/kubernetes-power-manager/controllers.(*PowerNodeReconciler).Reconcile(0xc0009c73c0, {0xc000c07000?, 0xc000be0e70?}, {{{0xc00048c1a0?, 0x10?}, {0xc00048c190?, 0x40d807?}}})
        /workspace/controllers/powernode_controller.go:133 +0x5f4
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x1a1bb50?, {0x1a1bbf8?, 0xc000be0e70?}, {{{0xc00048c1a0?, 0x16f9280?}, {0xc00048c190?, 0x4041f4?}}})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:121 +0xc8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000309860, {0x1a1bb50, 0xc0002406c0}, {0x16307c0?, 0xc000482200?})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:320 +0x33c
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000309860, {0x1a1bb50, 0xc0002406c0})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:230 +0x325
```

**Comment by catblade** [comment]
@shaorui0 Can you please give K8s version, OS, and kernel version? And perhaps which example?
